export const loginStyles = {
    wrap: {
        minHeight: "100dvh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        background: "#0b1020",
        padding: 16,
    },
    card: {
        width: "100%",
        maxWidth: 420,
        background: "#11162a",
        color: "#e7e9f3",
        border: "1px solid #232a4a",
        borderRadius: 16,
        padding: 24,
        boxShadow: "0 10px 30px rgba(0,0,0,.35)",
        display: "flex",
        flexDirection: "column",
        gap: 12,
    },
    label: { display: "flex", flexDirection: "column", gap: 6, fontSize: 14 },
    input: {
        height: 44,
        borderRadius: 10,
        border: "1px solid #2a335c",
        background: "#0b1020",
        color: "#e7e9f3",
        padding: "0 12px",
        outline: "none",
    },
    eyeBtn: {
        position: "absolute",
        right: 8,
        top: 6,
        height: 32,
        padding: "0 10px",
        borderRadius: 8,
        border: "1px solid #2a335c",
        background: "#0b1020",
        color: "#e7e9f3",
        cursor: "pointer",
    },
    rowBetween: { display: "flex", justifyContent: "space-between", alignItems: "center" },
    checkLabel: { display: "flex", alignItems: "center", gap: 8, color: "#c3c7da", fontSize: 14 },
    primaryBtn: {
        height: 44,
        borderRadius: 10,
        border: "1px solid #4158d0",
        background: "linear-gradient(90deg,#4158d0,#c850c0)",
        color: "white",
        fontWeight: 600,
        cursor: "pointer",
    },
    secondaryBtn: {
        height: 44,
        borderRadius: 10,
        border: "1px solid #2a335c",
        background: "#0b1020",
        color: "#e7e9f3",
        cursor: "pointer",
        padding: "0 12px",
    },
    error: {
        background: "#2a1316",
        color: "#ffb4b4",
        border: "1px solid #7a271a",
        padding: 10,
        borderRadius: 10,
        fontSize: 14,
    },
}